### ISSUE TITLE
言オリ記事作成

### ISSUE THREAD

**Issue by Pudding-kun** [hulinguistics/huling#100]
## 💡 Summary

言オリの記事を作成する（このissueは永久に閉じない）

**Comment by Pudding-kun** [comment]
新記事作成しても自動でサイドバーには反映されないんですね（現状JOL2017-3のモンゴル語が反映されてない）

**Comment by xiupos** [comment]
Related to #60

**Comment by xiupos** [comment]
#318 したので閉じる
