### ISSUE TITLE
古教会スラヴ語

### ISSUE THREAD

**Issue by Miyadaj** [hulinguistics/huling#122]
## 💡 Summary

古代教会スラヴ語の記事を書く. 木村(1985)『古代教会スラブ語入門』などを参考にする.

**Comment by xiupos** [comment]
ブランチ作成しました
https://github.com/hulinguistics/huling/blob/article/122-chu/src/docs/chu/index.md ([編集](https://github.com/hulinguistics/huling/edit/article/122-chu/src/docs/chu/index.md))

**Comment by xiupos** [comment]
フォントについて，現在古教会スラヴ語用に使っているフォント'Monomakh Unicode'は太字と斜字のフォントセットが無いためそれらが使えない．太字と斜字を使う場合は他のフォントを探してくる必要がありあそう

**Comment by xiupos** [comment]
[CMS上](https://huling.org/edit#/collections/docs/entries/chu)に移しました
