### ISSUE TITLE
目標解答時間の追加

### ISSUE THREAD

**Issue by yuta-sasaki-8128** [hulinguistics/huling#127]
## 💡 Summary

既存の言オリ解説記事に目標解答時間を追加したい。
基準をある程度統一するため、宮本くんか樗木さんあたりにお願いしたいです。

**Comment by xiupos** [comment]
目標回答時間ですが、単純に $(手順) \times \alpha$ ( $\alpha$ は定数) と定義してしまって良いと思います。あとえば見出し1個3分など
