### ISSUE TITLE
言オリ解説記事かく

### ISSUE THREAD

**Issue by xiupos** [hulinguistics/huling#13]
## 💡 Summary

とりあえずプリンくんが公開している記事を全て移植したい

**Comment by Pudding-kun** [comment]
少なくともJOLに関しては全問揃えたいですね(本番デプロイまでには間に合わないけど)

**Comment by Pudding-kun** [comment]
というか今更ですけど、人に見せる用に書いてなかったのでかなり内容が不正確なんですよね
デプロイの前に今ある分はre-writeしないとダメかも

**Comment by xiupos** [comment]
とりあえずあるものは全部移したので，いい感じにre-writeおねがいします．
