### ISSUE TITLE
言語概説: ロシア語の改訂

### ISSUE THREAD

**Issue by xiupos** [hulinguistics/huling#135]
## 💡 Summary

先生に頂いたアドバイスを基に改訂する。まずは頂いたアドバイスをまとめ、やることをリスト化する。

**Comment by xiupos** [comment]
- [ ] Я один, мы одниとかの違いを説明してくれる画像のある例文
- [ ] 「直説法」「直接法」の表記揺れ
- [ ] 与格の例の「давала」→完了体「дала」
- [ ] 対格の例の「целует」→「видит」
- [ ] 造格の例の「увлекается」→「разговаривает со」「была」、または道具で「Она пишет карандашом」
- [ ] 語順: 一般的な語順と強調表現の追加
- [ ] 音素: 「ィ」について修正
- [ ] 文字「Ёё」の初出に関する訂正
- [ ] 所有表現「иметь」に関する追加

**Comment by Miyadaj** [comment]
与格の例の「давала」→完了体「дала」
については最新版で既に訂正してある

**Comment by xiupos** [comment]
ご協力ありがとうございました
