### ISSUE TITLE
ロゴとヘッダー画像作り直す

### ISSUE THREAD

**Issue by xiupos** [hulinguistics/huling#14]
## 💡 Summary

パワポで作られたというロゴとヘッダー画像を作り直したい。画質的問題。できればSVGにしてしまいたい

**Comment by Pudding-kun** [comment]
ダークモードに切り替えたときにトップページのヘッダーだけ白いのガチで気持ち悪いので誰か透過画像にして上げ直してください(他力本願)
っていうかロゴもヘッダーもグリーンにしませんか？

**Comment by xiupos** [comment]
テーマカラーについてはおそらく変更できるので、そっちを青系に変えるのもありかと思います（[参考](https://miyauchi.dev/posts/start-vitepress/#custom-css)）

**Comment by xiupos** [comment]
一応変えてみました，良さげならPRをmergeしちゃってください
