### ISSUE TITLE
Docsに「研究発表」欄が欲しい

### ISSUE THREAD

**Issue by tetuinngotto361** [hulinguistics/huling#211]
## 💡 Summary

Docsに「研究発表」欄や「雑記」欄などが欲しい。気軽に投稿できるようなページがあればいろいろな人が寄稿しやすくなるはず。

**Comment by xiupos** [comment]
`/src/docs/posts/`以下に記事を作成し，Front Matterで`section: 雑記`にすれば雑記として追加できます
