### ISSUE TITLE
研究記事「変態による変態のための"変体"仮名講座—春画を読めるようになろう！—」

### ISSUE THREAD

**Issue by tetuinngotto361** [hulinguistics/huling#212]
## 💡 Summary

いつか作るのでお願いします。
新しく作ってほしい「研究発表」欄か、日本語の欄か、どこかに書きたい。

**Comment by xiupos** [comment]
related to #211

**Comment by tetuinngotto361** [comment]
語族ごとの記事を作るなら、#211 で提起した「研究発表」欄をなくして、「語族-アルタイ語族-日本語」の中においてもいいかもしれない。
あるいは、「研究発表-語族-アルタイ語族-日本語」の中でもいいかもしれない。

related to #207

**Comment by xiupos** [comment]
![image](https://user-images.githubusercontent.com/26175482/197928727-9c0d6545-4867-437d-90d1-37dff4b69b2f.png)
ISO639-5に沿って言語を階層的に管理したい．サイドバーに階層表示は無いため実装が必要

**Comment by xiupos** [comment]
空記事追加しました．以下の「Edit on Web」から編集できます．

| | Links |
| :-- | :-- |
| 🪵 Branch | [`212-hentai`](https://github.com/hulinguistics/huling/tree/212-hentai) |
| ✏ Post | [`src/docs/ara/index.md`](https://github.com/hulinguistics/huling/blob/212-hentai/src/docs/post/hentaigana/index.md) ([Edit on Web](https://github.com/hulinguistics/huling/edit/212-hentai/src/docs/post/hentaigana/index.md)) |
| ☁ Preview | [here](https://212-hentai.huling-dev.pages.dev/docs/post/hentaigana/) (please wait a few mins) |

**Comment by xiupos** [comment]
CMS導入のためclose
