### ISSUE TITLE
表のセル結合

### ISSUE THREAD

**Issue by Miyadaj** [hulinguistics/huling#243]
## 💡 Summary

指定した場所で表のセルを結合できるようになったら嬉しい.
（md033 を切って html を使うしかないのなら現状のままで良い）

## Why

たとえば格変化表などを作成するとき, 男性と中性が同形になることがあるため. それ以外にも使える場面は多そう.

**Comment by xiupos** [comment]
わかる欲しい

**Comment by Miyadaj** [comment]
これいいね.
結合してほしくないところまで結合してしまうのが難点かもしれないけど, それもゼロ幅スペースかなんかで一応対処できそうだし.

**Comment by xiupos** [comment]
現時点で結合したら困るもの探してみて、無さそうor解決できそうならもう導入しちゃうか

**Comment by Miyadaj** [comment]
たとえばロシア語の形容詞の語尾で
男性・中性の主・対格以外の格はまとめたいけど,
女性の -oj という語尾はまとめたくない.
(今でこそ同じ形に見えるけどそれぞれ別の形式から変化したものだから)

|(sg)|m|n|f|
|:--:|:--:|:--:|:--:|
|nom|-yj|-oe|-aja|
|gen|-ogo|-ogo|-oj|
|dat|-omu|-omu|-oj|
|acc|-yj / -ogo|-oe|-uju|
|instr|-ym|-ym|-oj|
|loc|-om|-om|-oj|

-oj のあとに適当な非表示文字入れたら解決できる気がするけど, どうなんだろ

**Comment by xiupos** [comment]
うむむ
ちなみになんだけど，もしこの記法が使えたら便利？↓
https://b1san-blog.com/post/vscode/vscode-md-jointable/

**Comment by Miyadaj** [comment]
あーそれ前にVSCodeで使ったことある.

実際に使う場面を考えたら
[Menci/markdown-it-merge-cells](https://github.com/Menci/markdown-it-merge-cells)
より
https://b1san-blog.com/post/vscode/vscode-md-jointable/
の方が便利なのかもしれない

**Comment by xiupos** [comment]
「空欄で左と連結する」仕様についてはどう思う？

**Comment by Miyadaj** [comment]
↓こういう空欄多めの表つくったら形崩れるのが難点

| |唇音|歯茎音|硬口蓋音|軟口蓋音|
|:---:|:---:|:---:|:---:|:---:|
|**破裂音**|p b|t d| ​|k g|
|**破擦音**| ​|c dz|č|​ |
|**摩擦音**|v|s z|š ž|x|
|**鼻音**|m|n|ń| ​|
|**流音**|​ |l r|ľ ŕ|​ |
|**半母音**| ​|​ |j| ​|

**Comment by xiupos** [comment]
やっぱこの仕様いらんよね，「>」と「^」だけほしい

**Comment by xiupos** [comment]
`>`と`^`で表のセルが結合されるようになったよ

**Comment by Miyadaj** [comment]
毎度のことながら頼りに成増
