### ISSUE TITLE
ページ遷移後のスクロール

### ISSUE THREAD

**Issue by Miyadaj** [hulinguistics/huling#293]
## 💡 Summary

特に文字変換器のページで，HLConverter を読み込むのにコンマ何秒かかかる関係で
リンクをたどっても URL で指定した位置より上の方で止まってしまう．
ページ遷移後に指定した位置まで自動でスクロールするように改善したい．

動作確認：[コプト文字変換器のリンク](https://huling.org/docs/tools/conv/#%E3%82%B3%E3%83%95%E3%82%9A%E3%83%88%E8%AA%9E%E3%82%B3%E3%83%95%E3%82%9A%E3%83%88%E6%96%87%E5%AD%97)

## Why

コプト文字変換器を依頼してくれた彼からのフィードバックにより．
自分も前々から気になってはいた．

**Comment by xiupos** [comment]
根本的な解決として，文字変換器ごとにページを分けたい気もする

**Comment by Miyadaj** [comment]
変換器ごとにページを分けることについても，検討を加速し適切に対応していきたい．
個別ページを立てると[こんな風に](https://www.lexilogos.com/keyboard/russian_conversion.htm)

- 説明文を details に折りたたまずに表示できる
- `textarea` を大きくできる

などの利点がある．

また，今後「便利機能」に文字変換器以外のもの（#191 の地図など）が
追加される可能性も念頭に置くと，セクションの分け方を少し考え直したい．
現行の Docs 一本では内容的に収まりきらない気がする．
ここまでの流れ：#192 #194 #214 #239
