### ISSUE TITLE
リダイレクト実装

### ISSUE THREAD

**Issue by Miyadaj** [hulinguistics/huling#438]
## 💡 Summary

Huling の旧url からリダイレクトを。

## 淮河？

記事構成が変わるたびにリンク切れを起こすとサイトとして良くない気がするから。
[ロシア語 | 北海道大学 外国語教育センター](https://www.imc.hokudai.ac.jp/lang/languages/russian.php.html)にあるリンクが切れているのを発見した
- https://huling.org/docs/rus/index.html : 404 page not found
- https://huling.org/docs/rus : 有効

気が向いたらで良いので、お願いします（自分ではできない）

**Comment by xiupos** [comment]
まじか

**Comment by xiupos** [comment]
リダイレクト設定した。
リダイレクト、Cloudflareだと無料で3ルールしか設定できなくて躊躇してる。だいたい1$/ルールで追加できる(5ルール単位)

**Comment by xiupos** [comment]
https://developers.cloudflare.com/pages/platform/redirects/
これ試すか

**Comment by Miyadaj** [comment]
感謝感激
