### ISSUE TITLE
SNS共有ボタンの追加

### ISSUE THREAD

**Issue by Pudding-kun** [hulinguistics/huling#64]
## 💡 Summary

ブログにありがちなSNS共有ボタン (少なくともTwitter共有ボタン) が記事上部・記事下部に欲しいかも
ブラウザ側の機能で共有できるけど、サイト側に実装しておきたい感はある

**Comment by xiupos** [comment]
VitePressにはそういった機能は無いので，実装が必要ですね．Vueコンポーネントで作成して記事毎に貼るのが現実的ですが，スマートではないので要検証です

**Comment by ACamus-Git** [comment]
ボタンのテンプレートはこんな感じですかね
<a href="https://twitter.com/share"
   class="twitter-share-button"
   data-via="HU_Linguistic"
   data-text="日本言語学オリンピック2019年大問4イヌクティトゥット語の解説 by北大言語学サークル(Huling)"
   data-lang="ja"
   data-url="https://murashun.jp/">Tweet</a>

**Comment by Pudding-kun** [comment]
単なるリンクじゃなくてTwitterのアイコンのボタンにしたくないですか？

**Comment by xiupos** [comment]
ブラウザの共有ボタンを使えばヨシ
