### ISSUE TITLE
句読点の統一

### ISSUE THREAD

**Issue by xiupos** [hulinguistics/huling#77]
## 💡 Summary

句読点の表記法に揺れがあるので，いずれかの表記法に統一したい

**Comment by Miyadaj** [comment]
全角カンマ・全角ピリオドに統一するのが良い気がしてきた．

**Comment by xiupos** [comment]
textlintとかの導入を検討すべきかも

**Comment by Miyadaj** [comment]
いま気付いた問題点
- markdown で全角カンマ＋改行をするとカンマのあとに半角スペースが入ってしまうため，見た目が少し悪くなる
